
#─────────────────────────────────────────────────────────────────────────
# Anywhere that uses IDs, such as blocks, biomes, dimensions, and structures, also supports:
# • Tags (e.g. "#minecraft:is_underground")
# • Comma-separated lists (e.g. "minecraft:desert,#minecraft:is_badlands")
#     Applies the setting to all listed IDs. Can use tags, regular IDs, and negation interchangeably
# • Negation (e.g. "!minecraft:jungle_leaves")
#     Useful with lists/tags. Excludes the listed IDs from the setting
#     i.e. "#minecraft:leaves,!minecraft:jungle_leaves" (all leaves EXCEPT jungle leaves)
# Settings with "//v" will list elements vertically. Removing "//v" will list elements in one line
#─────────────────────────────────────────────────────────────────────────
[Dimensions]
	#─────────────────────────────────────────────────────────────────────────//v
	# Applies an offset to the world's temperature across an entire dimension
	# ├── Format: [["dimension_id", temperature, *units], [...], etc]
	# └── [* = optional]
	# • dimension_id: The ID of the dimension (e.g. "minecraft:the_nether")
	# • temperature: The temperature offset to apply to the dimension
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	"Dimension Temperature Offsets" = [
	    ["minecraft:the_nether", 32, "f"],
	    ["minecraft:the_end", -5, "f"],
	    ["twilightforest:twilight_forest_type", 10, "f"]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the temperature of a dimension, overriding biome and elevation temperature
	# ├── Format: [["dimension_id", temperature, *units], [...], etc]
	# └── [* = optional]
	# • dimension_id: The ID of the dimension (e.g. "minecraft:the_nether")
	# • temperature: The temperature of the dimension
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	"Dimension Temperatures" = []

[Biomes]
	#─────────────────────────────────────────────────────────────────────────//v
	# Applies an offset to the temperature of a biome
	# ├── Format: [["biome_id", lowTemp, highTemp, *units, *waterTemp], [...], etc]
	# └── [* = optional]
	# • biome_id: The ID of the biome (e.g. "minecraft:desert")
	# • lowTemp: The temperature offset at midnight
	# • highTemp: The temperature offset at noon
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	# • *waterTemp: Offsets the temperature of water in the biome
	"Biome Temperature Offsets" = []
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the temperature of a biome, overriding the biome's default temperature
	# ├── Format: [["biome_id", lowTemp, highTemp, *units, *waterTemp], [...], etc]
	# └── [* = optional]
	# • biome_id: The ID of the biome (e.g. "minecraft:desert")
	# • lowTemp: The temperature of the biome at midnight
	# • highTemp: The temperature of the biome at noon
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	# • *waterTemp: The temperature of water in the biome
	"Biome Temperatures" = [
	    ["minecraft:soul_sand_valley", 53, 53, "F"],
	    ["minecraft:old_growth_birch_forest", 58, 72, "F"],
	    ["minecraft:river", 60, 70, "F"],
	    ["minecraft:swamp", 72, 84, "F", -5],
	    ["minecraft:savanna", 70, 95, "F"],
	    ["minecraft:savanna_plateau", 76, 98, "F"],
	    ["minecraft:windswept_savanna", 67, 90, "F"],
	    ["minecraft:taiga", 44, 62, "F"],
	    ["minecraft:snowy_taiga", 8, 38, "F", -15],
	    ["minecraft:old_growth_pine_taiga", 48, 62, "F"],
	    ["minecraft:old_growth_spruce_taiga", 48, 62, "F"],
	    ["minecraft:desert", 48, 115, "F"],
	    ["minecraft:stony_shore", 50, 64, "F"],
	    ["minecraft:snowy_beach", 8, 38, "F", -15],
	    ["minecraft:snowy_slopes", 24, 32, "F", -15],
	    ["minecraft:windswept_forest", 48, 66, "F"],
	    ["minecraft:frozen_peaks", 15, 31, "F", -18],
	    ["minecraft:warm_ocean", 67, 76, "F", 5],
	    ["minecraft:frozen_ocean", 20, 31, "F", -20],
	    ["minecraft:deep_frozen_ocean", 20, 31, "F", -20],
	    ["minecraft:jungle", 76, 87, "F"],
	    ["minecraft:bamboo_jungle", 76, 87, "F"],
	    ["minecraft:badlands", 84, 120, "F", -5],
	    ["minecraft:wooded_badlands", 80, 108, "F", -5],
	    ["minecraft:eroded_badlands", 88, 120, "F", -5],
	    ["minecraft:deep_dark", 63, 63, "F"],
	    ["minecraft:dripstone_caves", "disable"],
	    ["tfc:low_canyons", 58, 72, "F"],
	    ["tfc:mountains", 58, 72, "F"],
	    ["tfc:volcanic_mountains", 76, 90, "F"],
	    ["tfc:badlands", 84, 120, "F"],
	    ["tfc:lake", 44, 62, "F"],
	    ["tfc:plateau_lake", 44, 62, "F"],
	    ["tfc:old_mountains", 44, 62, "F"],
	    ["tfc:volcanic_oceanic_mountains", 76, 90, "F"],
	    ["tfc:highlands", 44, 62, "F"],
	    ["tfc:canyons", 59, 70, "F"],
	    ["tfc:plains", 59, 72, "F"],
	    ["tfc:hills", 59, 70, "F"],
	    ["tfc:rolling_hills", 59, 70, "F"],
	    ["tfc:volcanic_mountain_lake", 76, 90, "F"],
	    ["tfc:oceanic_mountains", 44, 65, "F"],
	    ["tfc:deep_ocean_trench", 44, 65, "F"],
	    ["tfc:river", 60, 70, "F"],
	    ["tfc:ocean", 44, 65, "F"],
	    ["tfc:deep_ocean", 44, 50, "F"],
	    ["tfc:tidal_flats", 59, 59, "F"],
	    ["tfc:plateau", 59, 65, "F"],
	    ["tfc:volcanic_oceanic_mountain_lake", 76, 90, "F"],
	    ["tfc:salt_marsh", 59, 65, "F"],
	    ["tfc:ocean_reef", 44, 65, "F"],
	    ["tfc:old_mountain_lake", 44, 65, "F"],
	    ["tfc:inverted_badlands", 84, 120, "F"],
	    ["tfc:oceanic_mountain_lake", 44, 65, "F"],
	    ["tfc:lowlands", 59, 65, "F"],
	    ["tfc:mountain_lake", 44, 65, "F"]
	]

[Blocks]
	#─────────────────────────────────────────────────────────────────────────//v
	# Applies temperature-emitting properties to blocks
	# ├── Format: [["block_id", temperature, range, *units, *maxEffect, *"predicates", *"{nbt}", *tempLimit], [...], etc]
	# └── [* = optional]
	# • block_id: The ID of the block (i.e. "minecraft:lava")
	# • temperature: The temperature of the block, in Minecraft units
	# • range: The radius of the block's temperature effect, in blocks
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	# • *maxEffect: The maximum cumulative temperature change this block can cause to a player (even with multiple blocks)
	# • *predicates: The state that the block must have for the temperature to be applied (i.e. "lit=true").
	#   (Define multiple predicates by separating them with commas [i.e. "lit=true,waterlogged=false"])
	# • *nbt: The NBT data that the block must have for the temperature to be applied.
	# • *tempLimit: The maximum world temperature at which this block temp will have any effect.
	#   (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [
	    ["cold_sweat:boiler", 12, 7, "f", 36, "lit=true", "", 212],
	    ["cold_sweat:icebox", -12, 7, "f", 36, "frosted=true", "", 32],
	    ["minecraft:lava", 20, 7, "f", 200, "", "", 1000, true],
	    ["#minecraft:fire", 15, 7, "f", 45, "", "", 400],
	    ["#minecraft:campfires", 15, 7, "f", 45, "lit=true", " ", 400],
	    ["#forge:magma_block", 5, 2, "f", 30],
	    ["minecraft:lava_cauldron", 20, 7, "f", 200, "", "", 1000, true],
	    ["minecraft:ice", -6, 4, "f", 24, "", "", 33],
	    ["minecraft:packed_ice", -12, 4, "f", 48, "", "", 16],
	    ["minecraft:blue_ice", -16, 4, "f", 64, "", "", 0],
	    ["#minecraft:ice", -6, 4, "f", 27, "", "", 33],
	    ["create:blaze_burner", 5, 3, "f", 30, "blaze=smouldering", "", 400],
	    ["create:blaze_burner", 10, 4, "f", 30, "blaze=fading", "", 400],
	    ["create:blaze_burner", 15, 5, "f", 45, "blaze=kindled", "", 400],
	    ["create:blaze_burner", 20, 6, "f", 60, "blaze=seething", "", 400]
	]
	#─────────────────────────────────────────────────────────────────────────
	# The maximum range of blocks' area of effect
	# - Note: This will not change anything unless blocks are configured to utilize the expanded range
	# - This value is limited to 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 8
	#─────────────────────────────────────────────────────────────────────────
	# When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Behavior" = true
	#─────────────────────────────────────────────────────────────────────────
	# When set to true, modifies ice blocks to be harvestable with a pickaxe
	"Custom Ice Drops" = true
	#─────────────────────────────────────────────────────────────────────────
	# The speed at which wet players dry off
	#Range: 0.0 ~ Infinity
	"Dryoff Speed" = 0.0015
	#─────────────────────────────────────────────────────────────────────────
	# The speed at which players become soaked when in water
	#Range: 0.0 ~ Infinity
	"Water Soak Speed" = 0.1
	#─────────────────────────────────────────────────────────────────────────
	# The speed at which players become soaked when in rain
	#Range: 0.0 ~ Infinity
	"Rain Soak Speed" = 0.0125
	#─────────────────────────────────────────────────────────────────────────
	# The default temperature of water
	# └── Format: [temperature, *units]
	"Default Water Temperature" = [-10, "f"]
	#─────────────────────────────────────────────────────────────────────────
	# The maximum soak level a player can reach from rain alone (0.0 - 1.0)
	#Range: 0.0 ~ Infinity
	"Max Rain Soak" = 0.2

[Structures]
	#─────────────────────────────────────────────────────────────────────────
	# Overrides the world temperature when the player is within this structure
	# ├── Format: [["structure_id", temperature, *units], [...], etc]
	# └── [* = optional]
	# • structure_id: The ID of the structure (i.e. "minecraft:stronghold")
	# • temperature: The temperature of the structure, in Minecraft units
	# • *units: The units of the temperature ("f" for Fahrenheit, "c" for Celsius, "mc" for Minecraft units)
	"Structure Temperatures" = []
	#─────────────────────────────────────────────────────────────────────────
	# Offsets the world temperature when the player is within this structure
	# ├── Format: [["structure_id", offset, *units], [...], etc]
	# └── [* = optional]
	# • structure_id: The ID of the structure (i.e. "minecraft:igloo")
	# • offset: The temperature offset of the structure, in Minecraft units
	# • *units: The units of the temperature ("f" for Fahrenheit, "c" for Celsius, "mc" for Minecraft units)
	"Structure Temperature Offsets" = []

[Misc]
	#─────────────────────────────────────────────────────────────────────────
	# A temperature offset applied when in complete shade or when the sky is overcast
	# └── Format: [offset, *units]
	"Shade Temperature Offset" = [-9, "f"]
	#─────────────────────────────────────────────────────────────────────────
	# List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	# Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = ["#comforts:sleeping_bags", "tfc:thatch_bed", "#minecraft:beds"]
	#─────────────────────────────────────────────────────────────────────────
	# When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#─────────────────────────────────────────────────────────────────────────
	# Converts damage dealt by Soul Fire to cold damage (default: true)
	# Does not affect the block's temperature
	"Cold Soul Fire" = true

#"Thermal sources" are blocks that have a smokestack and give frigidness/warmth. like the hearth, boiler, and iceobx
["Thermal Sources"]
	#─────────────────────────────────────────────────────────────────────────
	# How effective thermal sources are at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Thermal Source Strength" = 0.75
	#─────────────────────────────────────────────────────────────────────────
	# List of additional blocks that thermal sources can spread through
	# Use this list if thermal sources aren't spreading through particular blocks that they should
	"Thermal Source Spread Whitelist" = ["#forge:metal_bars", "#minecraft:leaves", "create:encased_fluid_pipe"]
	#─────────────────────────────────────────────────────────────────────────
	# List of additional blocks that thermal sources spread through
	# Use this list if thermal sources are spreading through particular blocks that they shouldn't
	"Thermal Source Spread Blacklist" = ["minecraft:water"]

	["Thermal Sources".Hearth]
		#─────────────────────────────────────────────────────────────────────────
		# Allows the hearth to automatically turn on/off based on nearby players' temperature
		# If false, it turns on/off by redstone signal instead
		"Automatic Hearth" = false
		#─────────────────────────────────────────────────────────────────────────
		# The distance the hearth's air will travel from a source, like the hearth itself or the end of a pipe
		#Range: > 0
		"Hearth Range" = 20
		#─────────────────────────────────────────────────────────────────────────
		# The maximum distance that air can be piped away from the hearth
		#Range: > 0
		"Max Hearth Range" = 96
		#─────────────────────────────────────────────────────────────────────────
		# The maximum volume of the hearth's area of effect
		#Range: > 1
		"Hearth Volume" = 12000
		#─────────────────────────────────────────────────────────────────────────
		# The time it takes for the hearth to be fully functional after being placed
		#Range: > 0
		"Hearth Warm-Up Time" = 1200
		#─────────────────────────────────────────────────────────────────────────
		# The maximum amount of insulation that the hearth can provide
		#Range: 0 ~ 10
		"Hearth Effect Strength" = 10
		#─────────────────────────────────────────────────────────────────────────
		# How often the hearth consumes fuel (in ticks)
		# Lower numbers cause fuel to be consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Hearth Fuel Consumption Interval" = 40

	["Thermal Sources".Boiler]
		#─────────────────────────────────────────────────────────────────────────
		# Allows the boiler to automatically turn on/off based on nearby players' temperature
		# If false, it turns on/off by redstone signal instead
		"Automatic Boiler" = false
		#─────────────────────────────────────────────────────────────────────────
		# The distance the boiler's air will travel from a source, like the boiler itself or the end of a pipe
		#Range: > 0
		"Boiler Range" = 16
		#─────────────────────────────────────────────────────────────────────────
		# The maximum distance that air can be piped away from the boiler
		#Range: > 0
		"Max Boiler Range" = 96
		#─────────────────────────────────────────────────────────────────────────
		# The maximum volume of the boiler's area of effect
		#Range: > 1
		"Boiler Volume" = 2000
		#─────────────────────────────────────────────────────────────────────────
		# The time it takes for the boiler to be fully functional after being placed
		#Range: > 0
		"Boiler Warm-Up Time" = 1200
		#─────────────────────────────────────────────────────────────────────────
		# The maximum amount of insulation that the boiler can provide
		#Range: 0 ~ 10
		"Boiler Warmth Strength" = 5
		#─────────────────────────────────────────────────────────────────────────
		# How often the boiler consumes fuel (in ticks)
		# Lower numbers cause fuel to be consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Boiler Fuel Consumption Interval" = 40

	["Thermal Sources".Icebox]
		#─────────────────────────────────────────────────────────────────────────
		# Allows the icebox to automatically turn on/off based on nearby players' temperature
		# If false, it turns on/off by redstone signal instead
		"Automatic Icebox" = false
		#─────────────────────────────────────────────────────────────────────────
		# The distance the icebox's air will travel from a source, like the icebox itself or the end of a pipe
		#Range: > 0
		"Icebox Range" = 16
		#─────────────────────────────────────────────────────────────────────────
		# The maximum distance that air can be piped away from the icebox
		#Range: > 0
		"Max Icebox Range" = 96
		#─────────────────────────────────────────────────────────────────────────
		# The maximum volume of the icebox's area of effect
		#Range: > 1
		"Icebox Volume" = 2000
		#─────────────────────────────────────────────────────────────────────────
		# The time it takes for the icebox to be fully functional after being placed
		#Range: > 0
		"Icebox Warm-Up Time" = 1200
		#─────────────────────────────────────────────────────────────────────────
		# The maximum amount of insulation that the icebox can provide
		#Range: 0 ~ 10
		"Icebox Chill Strength" = 5
		#─────────────────────────────────────────────────────────────────────────
		# How often the icebox consumes fuel (in ticks)
		# Lower numbers cause fuel to be consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Icebox Fuel Consumption Interval" = 40

