
#General Settings
[general]
	#Base rpm creatures can spin the horse crank.
	#Range: > 1
	creatureRPMRange = 16
	#How much stress small creatures can produce for the horse crank.
	#Range: > 1
	smallCreatureStressRange = 128
	#How much stress medium creatures can produce for the horse crank.
	#Range: > 1
	mediumCreatureStressRange = 256
	#How much stress large creatures can produce for the horse crank.
	#Range: > 1
	largeCreatureStressRange = 512

#Path Category
[paths]
	#Types of blocks valid as "Poor" quality,
	poor_path_block = [
		"minecraft:dirt",
		"minecraft:grass_block",
		"tfc:dirt/silt",
		"tfc:dirt/loam",
		"tfc:dirt/sandy_loam",
		"tfc:dirt/silty_loam",
		"tfc:grass/silt",
		"tfc:grass/loam",
		"tfc:grass/sandy_loam",
		"tfc:grass/silty_loam"
	]
	#Types of blocks valid as "Normal" quality,
	normal_path_block = [
		"minecraft:dirt_path",
		"minecraft:gravel",
		"tfc:rock/gravel/granite",
		"tfc:rock/gravel/diorite",
		"tfc:rock/gravel/gabbro",
		"tfc:rock/gravel/shale",
		"tfc:rock/gravel/claystone",
		"tfc:rock/gravel/limestone",
		"tfc:rock/gravel/conglomerate",
		"tfc:rock/gravel/dolomite",
		"tfc:rock/gravel/chert",
		"tfc:rock/gravel/chalk",
		"tfc:rock/gravel/rhyolite",
		"tfc:rock/gravel/basalt",
		"tfc:rock/gravel/andesite",
		"tfc:rock/gravel/dacite",
		"tfc:rock/gravel/quartzite",
		"tfc:rock/gravel/slate",
		"tfc:rock/gravel/phyllite",
		"tfc:rock/gravel/schist",
		"tfc:rock/gravel/gneiss",
		"tfc:rock/gravel/marble",
		"tfc:grass_path/silt",
		"tfc:grass_path/loam",
		"tfc:grass_path/sandy_loam",
		"tfc:grass_path/silty_loam"
	]
	#Types of blocks valid as "Great" quality,
	great_path_block = [
		"minecraft:ice",
		"minecraft:packed_ice",
		"minecraft:blue_ice",
		"immersiveengineering:concrete",
		"immersiveengineering:concrete_brick",
		"immersiveengineering:concrete_tile",
		"car:asphalt",
	]

#Creature Category
[workers]
	#Valid "Small" creatures
	small_creatures = [
		"minecraft:wolf",
		"tfc:pig",
		"tfc:goat",
		"tfc:alpaca",
		"tfc:wolf",
		"tfc:dog"
	]
	#Valid "Medium" creatures
	medium_creatures = [
		"minecraft:cow",
		"tfc:cow",
		"tfc:donkey",
		"tfc:wildebeest"
	]
	#Valid "Large" creatures
	large_creatures = [
		"minecraft:horse",
		"tfc:yak",
		"tfc:musk_ox",
		"tfc:mule",
		"tfc:horse"
	]

