#IMPORTANT NOTICE:
#You can add more entries using KubeJS
#https://github.com/tom5454/Create-Ore-Excavation#kubejs
importantInfo = true
#Finite vein base amount
#Range: > 1
finiteAmountBase = 1000
#Veins infinite by default
defaultInfinite = false
#Max number of extractor per ore vein, Set to 0 for infinite
#Range: 0 ~ 64
maxExtractorsPerVein = 20
#Vein Finder 'Found Nearby' range in chunks
#Range: 1 ~ 8
veinFinderNear = 8
#Vein Finder accuracy for 'Found traces of ...'
#Range: 1 ~ 1000
veinFinderFar = 10
#Vein Finder use cooldown in ticks
#Range: 10 ~ 1000
veinFinderCd = 10

