
[general]
	#List of items to force-allow placing in the belt. Takes precedence over blacklist.
	whitelist = []
	#List of items to disallow from placing in the belt. (whitelist takes precedence)
	blacklist = [
		"firmalife:wood/big_barrel/acacia",
		"firmalife:wood/big_barrel/ash",
		"firmalife:wood/big_barrel/aspen",
		"firmalife:wood/big_barrel/birch",
		"firmalife:wood/big_barrel/blackwood",
		"firmalife:wood/big_barrel/chestnut",
		"firmalife:wood/big_barrel/douglas_fir",
		"firmalife:wood/big_barrel/hickory",
		"firmalife:wood/big_barrel/kapok",
		"firmalife:wood/big_barrel/mangrove",
		"firmalife:wood/big_barrel/maple",
		"firmalife:wood/big_barrel/oak",
		"firmalife:wood/big_barrel/palm",
		"firmalife:wood/big_barrel/pine",
		"firmalife:wood/big_barrel/rosewood",
		"firmalife:wood/big_barrel/sequoia",
		"firmalife:wood/big_barrel/sycamore",
		"firmalife:wood/big_barrel/white_cedar",
		"firmalife:wood/big_barrel/willow",
		"mekanism:personal_chest",
		"mekanism:basic_bin",
		"mekanism:advanced_bin",
		"mekanism:elite_bin",
		"mekanism:ultimate_bin",
		"immersiveengineering:metal_barrel",
		"tfc:powderkeg",
		"tfc:wood/barrel/acacia",
		"tfc:wood/barrel/ash",
		"tfc:wood/barrel/aspen",
		"tfc:wood/barrel/birch",
		"tfc:wood/barrel/blackwood",
		"tfc:wood/barrel/chestnut",
		"tfc:wood/barrel/douglas_fir",
		"tfc:wood/barrel/hickory",
		"tfc:wood/barrel/kapok",
		"tfc:wood/barrel/mangrove",
		"tfc:wood/barrel/maple",
		"tfc:wood/barrel/oak",
		"tfc:wood/barrel/palm",
		"tfc:wood/barrel/pine",
		"tfc:wood/barrel/rosewood",
		"tfc:wood/barrel/sequoia",
		"tfc:wood/barrel/sycamore",
		"tfc:wood/barrel/white_cedar",
		"tfc:wood/barrel/willow",
		"tfcastikorcarts:supply_cart/acacia",
		"tfcastikorcarts:supply_cart/ash",
		"tfcastikorcarts:supply_cart/aspen",
		"tfcastikorcarts:supply_cart/birch",
		"tfcastikorcarts:supply_cart/blackwood",
		"tfcastikorcarts:supply_cart/chestnut",
		"tfcastikorcarts:supply_cart/douglas_fir",
		"tfcastikorcarts:supply_cart/hickory",
		"tfcastikorcarts:supply_cart/kapok",
		"tfcastikorcarts:supply_cart/mangrove",
		"tfcastikorcarts:supply_cart/maple",
		"tfcastikorcarts:supply_cart/oak",
		"tfcastikorcarts:supply_cart/palm",
		"tfcastikorcarts:supply_cart/pine",
		"tfcastikorcarts:supply_cart/rosewood",
		"tfcastikorcarts:supply_cart/sequoia",
		"tfcastikorcarts:supply_cart/sycamore",
		"tfcastikorcarts:supply_cart/white_cedar",
		"tfcastikorcarts:supply_cart/willow",
		"tfcastikorcarts:plow/acacia",
		"tfcastikorcarts:plow/ash",
		"tfcastikorcarts:plow/aspen",
		"tfcastikorcarts:plow/birch",
		"tfcastikorcarts:plow/blackwood",
		"tfcastikorcarts:plow/chestnut",
		"tfcastikorcarts:plow/douglas_fir",
		"tfcastikorcarts:plow/hickory",
		"tfcastikorcarts:plow/kapok",
		"tfcastikorcarts:plow/mangrove",
		"tfcastikorcarts:plow/maple",
		"tfcastikorcarts:plow/oak",
		"tfcastikorcarts:plow/palm",
		"tfcastikorcarts:plow/pine",
		"tfcastikorcarts:plow/rosewood",
		"tfcastikorcarts:plow/sequoia",
		"tfcastikorcarts:plow/sycamore",
		"tfcastikorcarts:plow/white_cedar",
		"tfcastikorcarts:plow/willow",
		"tfcastikorcarts:animal_cart/acacia",
		"tfcastikorcarts:animal_cart/ash",
		"tfcastikorcarts:animal_cart/aspen",
		"tfcastikorcarts:animal_cart/birch",
		"tfcastikorcarts:animal_cart/blackwood",
		"tfcastikorcarts:animal_cart/chestnut",
		"tfcastikorcarts:animal_cart/douglas_fir",
		"tfcastikorcarts:animal_cart/hickory",
		"tfcastikorcarts:animal_cart/kapok",
		"tfcastikorcarts:animal_cart/mangrove",
		"tfcastikorcarts:animal_cart/maple",
		"tfcastikorcarts:animal_cart/oak",
		"tfcastikorcarts:animal_cart/palm",
		"tfcastikorcarts:animal_cart/pine",
		"tfcastikorcarts:animal_cart/rosewood",
		"tfcastikorcarts:animal_cart/sequoia",
		"tfcastikorcarts:animal_cart/sycamore",
		"tfcastikorcarts:animal_cart/white_cedar",
		"tfcastikorcarts:animal_cart/willow",
		"sns:frame_pack",
		"sns:leather_sack",
		"sns:burlap_sack",
		"sns:ore_sack",
		"supplementaries:sack"
	]
#When set to false, stackable items will no longer be allowed by default.
	allowAllNonStackableItems = true
