#EntityTypes allowed to pull wagons
allowed_entities = ["minecraft:horse","tfc:yak","tfc:musk_ox","tfc:mule","tfc:horse"]
#ID of the item (or tag, if starting with #) used to repair wagons
repair_material = "tfc_items:cast_iron_gear"
#The amount of durability regained per repair item.
#Range: > 0
repair_value = 20

["Conestoga Wagon Options"]
	#Maximum health
	#Range: > 0
	conestoga_wagon_health = 60
	#Speed (per level)
	#Range: 0.0 ~ 1.7976931348623157E308
	conestoga_wagon_speed = 0.1
	#Acceleration (seconds until maximum speed)
	#Range: 0.0 ~ 1.7976931348623157E308
	conestoga_wagon_acceleration = 2.0
	#Turn rate
	#Range: 0.0 ~ 1.7976931348623157E308
	conestoga_wagon_turn_rate = 2.0

["Royal Wagon Options"]
	#Maximum health
	#Range: > 0
	royal_wagon_health = 80
	#Speed (per level)
	#Range: 0.0 ~ 1.7976931348623157E308
	royal_wagon_speed = 0.15
	#Acceleration (seconds until maximum speed)
	#Range: 0.0 ~ 1.7976931348623157E308
	royal_wagon_acceleration = 3.0
	#Turn rate
	#Range: 0.0 ~ 1.7976931348623157E308
	royal_wagon_turn_rate = 2.0

["Armored Wagon Options"]
	#Maximum health
	#Range: > 0
	armored_wagon_health = 120
	#Speed (per level)
	#Range: 0.0 ~ 1.7976931348623157E308
	armored_wagon_speed = 0.1
	#Acceleration (seconds until maximum speed)
	#Range: 0.0 ~ 1.7976931348623157E308
	armored_wagon_acceleration = 4.0
	#Turn rate
	#Range: 0.0 ~ 1.7976931348623157E308
	armored_wagon_turn_rate = 2.0

