#Air qualities at different heights in different dimensions, with one string applying to one dimension.
#A basic entry consists of the dimension's identifier and the default air level in that dimension.
#Furthermore the quality at different heights can be overridden by defining a height range and a corresponding quality.
#If a dimension doesn't have an entry here, it'll be assumed to be green everywhere.
#The string entries use SNBT format, like vanilla commands do.
dimensions = ["{bounded_qualities: [{min: 0, max: 256, quality: \"green\"}], dimension: \"minecraft:overworld\", base_quality: \"yellow\"}", "{dimension: \"minecraft:the_nether\", base_quality: \"yellow\"}", "{dimension: \"minecraft:the_end\", base_quality: \"red\"}"]
#Whether to allow right-clicking torches to make them spray particle effects
enableSignalTorches = true
#How much air a Drowned attack removes. Set to 0 to disable this feature.
#Range: 0 ~ 72000
drownedChoking = 25

[Ranges]
	#The radius in which all blocks defined in the yellow air providers tag project a bubble of air around them.
	#Range: 1.0 ~ 32.0
	yellowAirProviderRadius = 6.0
	#The radius in which all blocks defined in the blue air providers tag (usually soul fire related blocks) project a bubble of air around them.
	#Range: 1.0 ~ 32.0
	blueAirProviderRadius = 6.0
	#The radius in which all blocks defined in the red air providers tag (usually lava related blocks) project a bubble of air around them.
	#Range: 1.0 ~ 32.0
	redAirProviderRadius = 3.0
	#The radius in which all blocks defined in the green air providers tag (usually various portal blocks) project a bubble of air around them.
	#Range: 1.0 ~ 32.0
	greenAirProviderRadius = 9.0

